apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: dev
  labels:
    app: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
